version: '3.6'
services:
  serin_db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3308:3306"
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
  serin_webserver:
    environment:
      - 'DB_HOST=serin_db'
      - 'DB_USER=root'
      - 'DB_PASSWORD=root'
      - 'DB_DATABASE=wish_list'
    image: webdevops/php-nginx
    ports:
      - "8021:80"
    volumes:
      - ./:/app